name: Release new version

on:
  workflow_dispatch:
    inputs:
      version-inc:
        description: "Increment major|minor|patch version"
        type: choice
        options:
          - major
          - minor
          - patch
        required: false
        default: 'patch'
      git-ref:
        description: 'Git Ref (Optional). Default: main'
        required: false
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ inputs.git-ref }}
    - name: Setup PNPM
      uses: pnpm/action-setup@v2.2.1
      with:
        version: 6
        run_install: "true"
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        cache: 'pnpm'
    - name: Increment ${{ inputs.version-inc  }}
      run: pnpm version ${{ inputs.version-inc  }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - run: pnpm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_REGISTRY_TOKEN }}
    - name: Create Release
      uses: release-drafter/release-drafter@v5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        publish: true