name: "🚀 Release new version"

on:
  workflow_dispatch:
    inputs:
      versionIncrement:
        description: "Increment major|minor|patch version"
        type: choice
        options:
          - major
          - minor
          - patch
        required: true
        default: 'patch'
      ref:
        description: 'Git Ref (Optional). Default: main'
        required: false
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.inputs.ref }}
    - name: Setup PNPM
      uses: pnpm/action-setup@v2.4.1
      with:
        version: 6
        run_install: "true"
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        cache: 'pnpm'
    - name: Increment ${{ github.event.inputs.versionIncrement }}
      run: pnpm version ${{ github.event.inputs.versionIncrement }}
    - run: |
        pnpm publish
        git push
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_REGISTRY_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Create Release
      uses: release-drafter/release-drafter@v5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        publish: true